# This file maintains the latest versions for all the CSM products in the given release
# The format is as follows:
# <product> : <version>

# CSM program version
csm-version : v1.15.0

# CSM Operator version
csm-operator : v1.10.0

# Driver versions
csi-powerscale : v2.15.0
csi-powerstore : v2.15.0
csi-powermax : v2.15.0
csi-vxflexos : v2.15.0
csi-unity : v2.15.0

# Module versions
csm-replication : v1.13.0
karavi-resiliency : v1.14.0
csm-authorization-v2 : v2.3.0
csireverseproxy : v2.14.0
karavi-observability : v1.13.0
karavi-metrics-powerflex : v1.13.0
csm-metrics-powerstore : v1.13.0
csm-metrics-powerscale : v1.10.0
csm-metrics-powermax : v1.8.0
karavi-topology : v1.13.0

# Tools
cert-csi : v1.9.0
dellctl : v1.15.0
karavictl : v1.15.0
repctl : v1.13.0
installation-wizard : 1.7.0

# Third Party Libraries referred in CSM
otel-collector : 0.130.1
nginx-unprivileged : 1.27
grafana : 11.5.2
prometheus : v2.34.0
openpolicyagent-opa : 0.70.0
openpolicyagent-kube-mgmt : 8.5.10
redis : 7.4.1-alpine

# CSI Sidecar versions
csi-resizer : v1.14.0
csi-provisioner : v5.3.0
csi-node-driver-registrar : v2.14.0
csi-attacher : v4.9.0
csi-external-health-monitor-controller : v0.15.0
csi-snapshotter : v8.3.0
